# Generated by Django 5.2.5 on 2025-08-18 10:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_devicetoken_created_at_devicetoken_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 18, 10, 26, 28, 320911, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 8, 18, 10, 26, 45, 180304, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
