# Generated by Django 5.2.5 on 2025-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_devicetoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_shop',
            field=models.TextField(default=''),
        ),
    ]
