# Generated by Django 5.2.5 on 2025-08-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_user_about_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
